dist: trusty
language: node_js
node_js:
- '8'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - npm test
    - npm run coverage
